name: test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

env:
  PYTHON_VERSION: '3.12'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: make pre-commit-install

      - name: Run lint
        run: make lint
